apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurelandingzone
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: azurelandingzone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: azurelandingzone
    spec:
      containers:
      - name: azurelandingzone
        image: containerregewus2.azurecr.io/containerregewus2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: Dev_ENVIRONMENT
          value: master
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:5000"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 5000
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: azurelandingzone
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: azurelandingzone
  externalTrafficPolicy: Local
