apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
        - name: samplewebapp 
          image: containerregewus2.azurecr.io/containerregewus2:latest
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: samplewebapp
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: samplewebapp