apiVersion: v1
kind: Service
metadata:
  name: azurelandingzone
  namespace: private
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "10.50.0.4"  # Optional specific private IP
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: "azurelandingzone-pls"
    service.beta.kubernetes.io/azure-pls-ip-configuration-subnet: "snet-alzspokerg-dev-eastus2-001"
    service.beta.kubernetes.io/azure-pls-ip-configuration-vnet: "vnet-alzspokerg-dev-eastus2-001"
    service.beta.kubernetes.io/azure-pls-ip-configuration-resource-group: "rg-alzspokerg-dev-eastus2-001"
    service.beta.kubernetes.io/azure-pls-ip-configuration-address-count: "1"
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
    service.beta.kubernetes.io/azure-pls-auto-approval: "5ab24318-463b-45a8-806d-cc2d0cf9a3d0" # Replace if needed
spec:
  type: LoadBalancer
  selector:
    app: azurelandingzone
  ports:
    - name: http
      port: 80
      targetPort: 5000